api_key:
  openrouter: <Input Your Own AK>


model:
  openrouter:
    - google/gemini-2.5-flash
    - openai/gpt-4o


base_url:
  openrouter: https://openrouter.ai/api/v1


window_size: 3
num_threads: 32
num_samples: 5
